#ifndef SIENNA_PAYLOAD_PROTOCOL_H
#define SIENNA_PAYLOAD_PROTOCOL_H

#define PROTO_VERSION  1
#define PROTO_MAGIC    0xA0
#define PROTO_DIAGNOSTIC 0xA1
#define PROTO_CRC_RECORD 0xA2
#define PROTO_BEGIN0   0xB0
#define PROTO_BEGIN1   0xB1
#define PROTO_REGION_BEGIN 0xB2
#define PROTO_REGION_LENGTH 0xB3
#define PROTO_REGION_END 0xB4
#define PROTO_STATUS   0xC0
#define PROTO_DATA     0xD0
#define PROTO_END      0xE0
#define PROTO_ERROR    0xEE
#define PROTO_OP_PROBE 1
#define PROTO_OP_PATCH 2
#define PROTO_OP_FACI_UNLOCK 3
#define PROTO_OP_FACI_PE_CYCLE 4
#define PROTO_OP_PATCH_V2 5
#define PROTO_OP_RESTORE 6
#define PROTO_OP_CRC_PROBE 7
#define PROTO_OP_PATCH_CRC 8
#define PROTO_OP_RAM_ECHO 9
#define PROTO_OP_RESTORE_SECTOR 10
#define PROTO_OP_VERIFY_CRC 11
#define PROTO_OP_CRC_INTERMEDIATE 12
#define PROTO_OP_WRITE_TARGET_CANDIDATE 13
#define PROTO_OP_WRITE_CRC_CANDIDATE 14
#define PROTO_OP_LIVE_READ 15

#define PROTO_CRC_ENTRY_CTL 0
#define PROTO_CRC_ENTRY_COUT 1
#define PROTO_CRC_RANGE_START 2
#define PROTO_CRC_RANGE_END 3
#define PROTO_CRC_ADJUST_ADDRESS 4
#define PROTO_CRC_OLD_ADJUST_WORD 5
#define PROTO_CRC_PATCHED_PREFIX_SW 6
#define PROTO_CRC_NEW_ADJUST_WORD 7
#define PROTO_CRC_ORIGINAL_SW_FULL 8
#define PROTO_CRC_PATCHED_SW_FULL 9
#define PROTO_CRC_ORIGINAL_DCRA_RAW 10
#define PROTO_CRC_PATCHED_DCRA_RAW 11
#define PROTO_CRC_EXIT_CTL 12
#define PROTO_CRC_EXIT_COUT 13
#define PROTO_CRC_SRAM_ECHO_LENGTH 14
#define PROTO_CRC_SRAM_ECHO_CRC32 15
#define PROTO_CRC_RECORD_COUNT 16

#endif
